version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  
  build:
    commands:
      - echo "Creating public directory if needed..."
      - mkdir -p public
      - cp index.html public/index.html 2>/dev/null || true
      - echo "Building application..."
      - npm run build
  
  post_build:
    commands:
      - echo "Build completed!"
      - ls -la build/ || ls -la

artifacts:
  files:
    - '**/*'
  base-directory: 'build'