version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "No dependencies to install"
  
  build:
    commands:
      - echo "No build step needed - static files"
  
  post_build:
    commands:
      - echo "Preparing static files..."
      - ls -la

artifacts:
  files:
    - '**/*'
  base-directory: '.'  # ← Prende tutti i file dalla root
