version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node version:"
      - node --version
      - npm --version
      
  pre_build:
    commands:
      - echo "Navigating to Frontend..."
      - cd Frontend
      - echo "Installing dependencies..."
      - npm ci --legacy-peer-deps || npm install --legacy-peer-deps

  build:
    commands:
      - echo "Building React app from root..."
      - cd Frontend && CI=false npm run build
      
  post_build:
    commands:
      - echo "Build completed"
      - ls -la Frontend/build/

artifacts:
  files:
    - '**/*'
  base-directory: Frontend/build
