version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 
    commands:
      - echo "Installing dependencies..."
      
  pre_build:
    commands:
      - echo "Starting clean install in Frontend directory..."
      - cd Frontend
      
      # Correzione: Pulizia e installazione approfondita
      - rm -rf node_modules
      - npm cache clean --force
      - npm install
      
      - cd ..

  build:
    commands:
      - echo "Starting React build..."
      # Esegue la compilazione all'interno della cartella Frontend
      - cd Frontend
      - CI=false npm run build 
      - echo "Build finished."
      - cd ..

  # NUOVA FASE: Sposta il contenuto compilato nella radice del contesto di CodeBuild
  post_build:
    commands:
      - echo "Staging final build files to artifact root..."
      
      # ** CRUCIALE: Copia il contenuto di Frontend/build nella radice (./) del contesto di build **
      # Questo assicura che index.html sia il primo file nello ZIP.
      - cp -R Frontend/build/. .
      
      # ** OPTIONAL: Se l'errore precedente era 'Frontend/Public' **
      # Potrebbe esserci un conflitto con il comando cp -R.
      # Rimuoviamo la cartella per evitare confusione se è stata creata:
      - rm -rf Frontend
      

# FASE FINALE: Definisce l'artefatto per il deployment
artifacts:
  files:
    # Indica a CodeBuild di includere TUTTO ciò che si trova nella radice del contesto di build (dove è stato copiato index.html)
    - '**/*'
    
  # Non usare base-directory. L'abbiamo risolta copiando i file.
