version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - cd Frontend
      - npm install

  build:
    commands:
      - echo "Building application..."
      - cd Frontend
      - npm run build
      
  post_build:
    commands:
      - echo "Build completed!"
      - cd Frontend
      - ls -la build/ || echo "Build folder not found"

artifacts:
  files:
    - '**/*'
  base-directory: Frontend/build
  discard-paths: no
