version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - npm --version
      - node --version
  
  build:
    commands:
      - echo "Building application..."
      - npm run build
  
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: 'build'  # Cambia in 'dist' o '.next' se usi Next.js
