version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 
    commands:
      - echo "Installing dependencies for Node.js 20..."
      
  pre_build:
    commands:
      - echo "Starting clean install in Frontend directory..."
      - cd Frontend
      
      # Correzione: Pulizia e installazione approfondita
      - rm -rf node_modules
      - npm cache clean --force
      - npm install
      
      - cd ..

  build:
    commands:
      - echo "Starting React build..."
      # Esegue la compilazione all'interno della cartella Frontend
      - cd Frontend
      - CI=false npm run build 
      - echo "Build finished."
      - cd ..
  
# FASE CRUCIALE: Definisce l'artefatto per il deployment
artifacts:
  files:
    - '**/*'
    
  # CORREZIONE FINALE DEL PATH: Sposta il contenuto della cartella 'build' 
  # nella radice dell'artefatto ZIP, risolvendo il problema dell'URL S3.
  base-directory: Frontend/Public
